### ISSUE TITLE
Create 'facility_calltimes' table and FacilityCalltime model

### ISSUE THREAD

**Issue by jessehorne** [Ameelio/connect-api#6]
facility_id
start (string, e.g "01:30", "14:30", "12:00", "15:15", etc) min:5, max:5
end (string, e.g "01:30", "14:30", "12:00", "15:15", etc) min:5, max:5
weekday (integer, 1=Monday, 2=Tuesday, etc...)
pod_id (nullable)

**Comment by dabbler0** [comment]
Questions/notes:
  - Do we want to generalize this to accommodate non-weekly rotations? Current model assumes everything repeats weekly.
