### ISSUE TITLE
Create 'inmates' table and Inmate model

### ISSUE THREAD

**Issue by jessehorne** [Ameelio/connect-api#9]
* number (string)
* pin (code to get into platform)
* first_name
* last_name
* facility_id
* pod_id
* dob (date of birth, date)
* race (string, nullable)
* sentence_length (float, years, nullable)
* sentence (string, nullable)
* quota (integer, number of calls per week)

**Comment by dabbler0** [comment]
Questions/notes:
  - Do we worry about pin theft? (i.e. do we need hashing here?)
  - Is there a reason we store `sentence_length` rather than expected release date?
